using TreeSitter.CodeGen.Emit;
using TreeSitter.CodeGen.Model;
using TreeSitter.CodeGen.Schema;

namespace TreeSitter.CodeGen;

/// <summary>
/// The public entry point of the typed-node generator. Pure and deterministic:
/// given the text of a grammar's <c>node-types.json</c> and a set of options, it
/// returns the C# source for the strongly-typed node wrappers. It does not touch
/// the filesystem or load any parser.
/// </summary>
public static class NodeTypesGenerator
{
    /// <summary>
    /// Generates typed-node bindings for one grammar.
    /// </summary>
    /// <param name="nodeTypesJson">The contents of the grammar's <c>node-types.json</c>.</param>
    /// <param name="options">Generation options (root namespace, language name).</param>
    /// <returns>The generated file(s) and summary counts.</returns>
    public static GeneratedGrammar Generate(string nodeTypesJson, GeneratorOptions options)
    {
        ArgumentNullException.ThrowIfNull(nodeTypesJson);
        ArgumentNullException.ThrowIfNull(options);

        IReadOnlyList<NodeType> nodeTypes = NodeTypesParser.Parse(nodeTypesJson);
        var registry = new TypeRegistry(options.RootNamespace, nodeTypes);

        var w = new CodeWriter();
        EmitHeader(w, options);

        var emitter = new StructEmitter(w, registry);

        int concrete = 0, supertype = 0, unnamed = 0;

        // Partition entries by category for tidy, deterministic namespacing.
        IReadOnlyList<TypeEntry> entries = registry.Entries;
        var rootEntries = entries.Where(e => e.Category is TypeCategory.Concrete or TypeCategory.Supertype).ToList();
        var unnamedEntries = entries.Where(e => e.Category == TypeCategory.Unnamed).ToList();
        var symbolEntries = entries.Where(e => e.Category == TypeCategory.Symbol).ToList();

        // --- root namespace: concrete nodes + supertypes ---
        w.OpenBrace($"namespace {options.RootNamespace}");
        foreach (TypeEntry e in rootEntries)
        {
            NodeType nt = registry.NodeFor(e);
            if (nt.IsSupertype)
            {
                emitter.EmitSupertype(e, nt);
                supertype++;
            }
            else if (HasAccessors(nt))
            {
                emitter.EmitConcrete(e, nt);
                concrete++;
            }
            else
            {
                emitter.EmitLeaf(e, nt);
                concrete++;
            }
            w.Blank();
        }
        w.CloseBrace();
        w.Blank();

        // --- Unnamed namespace ---
        if (unnamedEntries.Count > 0)
        {
            w.OpenBrace($"namespace {options.RootNamespace}.Unnamed");
            foreach (TypeEntry e in unnamedEntries)
            {
                emitter.EmitLeaf(e, registry.NodeFor(e));
                unnamed++;
                w.Blank();
            }
            w.CloseBrace();
            w.Blank();
        }

        // --- Symbols namespace (pure-punctuation tokens) ---
        if (symbolEntries.Count > 0)
        {
            w.OpenBrace($"namespace {options.RootNamespace}.Symbols");
            foreach (TypeEntry e in symbolEntries)
            {
                emitter.EmitLeaf(e, registry.NodeFor(e));
                unnamed++;
                w.Blank();
            }
            w.CloseBrace();
            w.Blank();
        }

        // --- AnonUnions namespace (must be emitted after all member types exist;
        //     order is irrelevant in C#, but we keep it last for readability) ---
        IReadOnlyList<AnonUnion> unions = registry.AnonUnions;
        if (unions.Count > 0)
        {
            w.OpenBrace($"namespace {options.RootNamespace}.AnonUnions");
            foreach (AnonUnion u in unions)
            {
                emitter.EmitUnion(u);
                w.Blank();
            }
            w.CloseBrace();
            w.Blank();
        }

        string fileName = $"{PascalLanguage(options.LanguageName)}.Nodes.g.cs";
        var file = new GeneratedFile(fileName, w.ToString());
        return new GeneratedGrammar([file], concrete, supertype, unnamed, unions.Count);
    }

    private static bool HasAccessors(NodeType nt) =>
        nt.Fields.Count > 0 || (nt.Children is { } c && c.Types.Count > 0);

    private static void EmitHeader(CodeWriter w, GeneratorOptions options)
    {
        w.Line("// <auto-generated/>");
        w.Line($"// Strongly-typed tree-sitter node wrappers for the '{options.LanguageName}' grammar.");
        w.Line("// Generated by TreeSitter.CodeGen from node-types.json. Do not edit by hand.");
        w.Line("#nullable enable");
        w.Line("#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member");
        w.Blank();
        w.Line("using TreeSitter;");
        w.Line("using TreeSitter.Typed;");
        w.Blank();
    }

    private static string PascalLanguage(string language)
    {
        if (language.Length == 0)
            return "Grammar";
        // Title-case the first letter; leave the rest (handles already-cased names).
        return char.ToUpperInvariant(language[0]) + language[1..];
    }
}
