// <auto-generated/>
// Strongly-typed tree-sitter node wrappers for the 'json' grammar.
// Generated by TreeSitter.CodeGen from node-types.json. Do not edit by hand.
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

using TreeSitter;
using TreeSitter.Typed;

namespace TreeSitter.Grammars.Json
{
    /// <summary>The <c>_value</c> supertype: any of its subtypes. Variants that are themselves supertypes are exposed transitively (their own subtypes are included in the accepted kinds).</summary>
    public readonly partial struct Value : global::TreeSitter.Typed.ITypedNode<Value>
    {

        /// <summary>The s-expression kind string for this node type.</summary>
        public const string Kind = "_value";

        /// <summary>The underlying untyped node.</summary>
        public global::TreeSitter.Node Node { get; }

        /// <summary>Wraps <paramref name="node"/> as a <see cref="Value"/> without any kind check.</summary>
        /// <param name="node">A node whose kind is already known to be accepted.</param>
        private Value(global::TreeSitter.Node node)
        {
            Node = node;
        }

        /// <summary>Determines whether a node of the given kind is accepted by this type.</summary>
        /// <param name="kind">A node kind string.</param>
        public static bool Accepts(string kind) => kind switch
        {
            "array" => true,
            "false" => true,
            "null" => true,
            "number" => true,
            "object" => true,
            "string" => true,
            "true" => true,
            _ => false,
        };

        /// <summary>Wraps the node if its kind is accepted, otherwise returns <see langword="null"/>.</summary>
        /// <param name="node">The node to wrap.</param>
        public static Value? TryFrom(global::TreeSitter.Node node) => !node.IsNull && Accepts(node.Kind) ? new Value(node) : null;

        /// <summary>Wraps the node without validation; a debug assert guards the kind. Use only when the kind is already known.</summary>
        /// <param name="node">An already-validated node.</param>
        public static Value FromUnchecked(global::TreeSitter.Node node)
        {
            global::System.Diagnostics.Debug.Assert(Accepts(node.Kind), "Node kind '" + node.Kind + "' is not valid for Value.");
            return new(node);
        }

        /// <summary>Discriminates which variant the wrapped node is.</summary>
        public enum Variant
        {
            /// <summary>The node matched no known variant.</summary>
            Unknown,
            /// <summary>The <c>array</c> variant.</summary>
            Array,
            /// <summary>The <c>false</c> variant.</summary>
            False,
            /// <summary>The <c>null</c> variant.</summary>
            Null,
            /// <summary>The <c>number</c> variant.</summary>
            Number,
            /// <summary>The <c>object</c> variant.</summary>
            Object,
            /// <summary>The <c>string</c> variant.</summary>
            String,
            /// <summary>The <c>true</c> variant.</summary>
            True,
        }

        /// <summary>The variant of the wrapped node. When variants overlap, the first declared variant that accepts the kind is reported.</summary>
        public Variant Which => Node.Kind switch
        {
            "array" => Variant.Array,
            "false" => Variant.False,
            "null" => Variant.Null,
            "number" => Variant.Number,
            "object" => Variant.Object,
            "string" => Variant.String,
            "true" => Variant.True,
            _ => Variant.Unknown,
        };

        /// <summary>The node as <see cref="TreeSitter.Grammars.Json.Array"/>, or <see langword="null"/> if it is a different variant.</summary>
        public TreeSitter.Grammars.Json.Array? AsArray() => TreeSitter.Grammars.Json.Array.TryFrom(Node);

        /// <summary>The node as <see cref="TreeSitter.Grammars.Json.False"/>, or <see langword="null"/> if it is a different variant.</summary>
        public TreeSitter.Grammars.Json.False? AsFalse() => TreeSitter.Grammars.Json.False.TryFrom(Node);

        /// <summary>The node as <see cref="TreeSitter.Grammars.Json.Null"/>, or <see langword="null"/> if it is a different variant.</summary>
        public TreeSitter.Grammars.Json.Null? AsNull() => TreeSitter.Grammars.Json.Null.TryFrom(Node);

        /// <summary>The node as <see cref="TreeSitter.Grammars.Json.Number"/>, or <see langword="null"/> if it is a different variant.</summary>
        public TreeSitter.Grammars.Json.Number? AsNumber() => TreeSitter.Grammars.Json.Number.TryFrom(Node);

        /// <summary>The node as <see cref="TreeSitter.Grammars.Json.Object"/>, or <see langword="null"/> if it is a different variant.</summary>
        public TreeSitter.Grammars.Json.Object? AsObject() => TreeSitter.Grammars.Json.Object.TryFrom(Node);

        /// <summary>The node as <see cref="TreeSitter.Grammars.Json.String"/>, or <see langword="null"/> if it is a different variant.</summary>
        public TreeSitter.Grammars.Json.String? AsString() => TreeSitter.Grammars.Json.String.TryFrom(Node);

        /// <summary>The node as <see cref="TreeSitter.Grammars.Json.True"/>, or <see langword="null"/> if it is a different variant.</summary>
        public TreeSitter.Grammars.Json.True? AsTrue() => TreeSitter.Grammars.Json.True.TryFrom(Node);

        /// <summary>Exhaustively maps over the variants, returning a value.</summary>
        public TResult Match<TResult>(global::System.Func<TreeSitter.Grammars.Json.Array, TResult> onArray, global::System.Func<TreeSitter.Grammars.Json.False, TResult> onFalse, global::System.Func<TreeSitter.Grammars.Json.Null, TResult> onNull, global::System.Func<TreeSitter.Grammars.Json.Number, TResult> onNumber, global::System.Func<TreeSitter.Grammars.Json.Object, TResult> onObject, global::System.Func<TreeSitter.Grammars.Json.String, TResult> onString, global::System.Func<TreeSitter.Grammars.Json.True, TResult> onTrue)
        {
            return Which switch
            {
                Variant.Array => onArray(TreeSitter.Grammars.Json.Array.FromUnchecked(Node)),
                Variant.False => onFalse(TreeSitter.Grammars.Json.False.FromUnchecked(Node)),
                Variant.Null => onNull(TreeSitter.Grammars.Json.Null.FromUnchecked(Node)),
                Variant.Number => onNumber(TreeSitter.Grammars.Json.Number.FromUnchecked(Node)),
                Variant.Object => onObject(TreeSitter.Grammars.Json.Object.FromUnchecked(Node)),
                Variant.String => onString(TreeSitter.Grammars.Json.String.FromUnchecked(Node)),
                Variant.True => onTrue(TreeSitter.Grammars.Json.True.FromUnchecked(Node)),
                _ => throw new global::TreeSitter.Typed.IncorrectNodeKindException(Node, "Value"),
            };
        }

        /// <summary>Exhaustively dispatches over the variants, performing an action.</summary>
        public void Switch(global::System.Action<TreeSitter.Grammars.Json.Array> onArray, global::System.Action<TreeSitter.Grammars.Json.False> onFalse, global::System.Action<TreeSitter.Grammars.Json.Null> onNull, global::System.Action<TreeSitter.Grammars.Json.Number> onNumber, global::System.Action<TreeSitter.Grammars.Json.Object> onObject, global::System.Action<TreeSitter.Grammars.Json.String> onString, global::System.Action<TreeSitter.Grammars.Json.True> onTrue)
        {
            switch (Which)
            {
                case Variant.Array: onArray(TreeSitter.Grammars.Json.Array.FromUnchecked(Node)); break;
                case Variant.False: onFalse(TreeSitter.Grammars.Json.False.FromUnchecked(Node)); break;
                case Variant.Null: onNull(TreeSitter.Grammars.Json.Null.FromUnchecked(Node)); break;
                case Variant.Number: onNumber(TreeSitter.Grammars.Json.Number.FromUnchecked(Node)); break;
                case Variant.Object: onObject(TreeSitter.Grammars.Json.Object.FromUnchecked(Node)); break;
                case Variant.String: onString(TreeSitter.Grammars.Json.String.FromUnchecked(Node)); break;
                case Variant.True: onTrue(TreeSitter.Grammars.Json.True.FromUnchecked(Node)); break;
                default: throw new global::TreeSitter.Typed.IncorrectNodeKindException(Node, "Value");
            }
        }

    }

    /// <summary>The <c>array</c> node.</summary>
    public readonly partial struct Array : global::TreeSitter.Typed.ITypedNode<Array>
    {

        /// <summary>The s-expression kind string for this node type.</summary>
        public const string Kind = "array";

        /// <summary>The underlying untyped node.</summary>
        public global::TreeSitter.Node Node { get; }

        /// <summary>Wraps <paramref name="node"/> as a <see cref="Array"/> without any kind check.</summary>
        /// <param name="node">A node whose kind is already known to be accepted.</param>
        private Array(global::TreeSitter.Node node)
        {
            Node = node;
        }

        /// <summary>Determines whether a node of the given kind is accepted by this type.</summary>
        /// <param name="kind">A node kind string.</param>
        public static bool Accepts(string kind) => kind == Kind;

        /// <summary>Wraps the node if its kind is accepted, otherwise returns <see langword="null"/>.</summary>
        /// <param name="node">The node to wrap.</param>
        public static Array? TryFrom(global::TreeSitter.Node node) => !node.IsNull && Accepts(node.Kind) ? new Array(node) : null;

        /// <summary>Wraps the node without validation; a debug assert guards the kind. Use only when the kind is already known.</summary>
        /// <param name="node">An already-validated node.</param>
        public static Array FromUnchecked(global::TreeSitter.Node node)
        {
            global::System.Diagnostics.Debug.Assert(Accepts(node.Kind), "Node kind '" + node.Kind + "' is not valid for Array.");
            return new(node);
        }
        /// <summary>The unnamed children (zero or more), with extras filtered out.</summary>
        public global::System.Collections.Generic.IEnumerable<TreeSitter.Grammars.Json.Value> Values
        {
            get
            {
                foreach (global::TreeSitter.Node child in global::TreeSitter.Typed.TypedNodeExtensions.FieldlessChildren(Node))
                {
                    if (TreeSitter.Grammars.Json.Value.TryFrom(child) is { } typed) yield return typed;
                }
            }
        }

    }

    /// <summary>The <c>comment</c> node.</summary>
    public readonly partial struct Comment : global::TreeSitter.Typed.ITypedNode<Comment>
    {

        /// <summary>The s-expression kind string for this node type.</summary>
        public const string Kind = "comment";

        /// <summary>The underlying untyped node.</summary>
        public global::TreeSitter.Node Node { get; }

        /// <summary>Wraps <paramref name="node"/> as a <see cref="Comment"/> without any kind check.</summary>
        /// <param name="node">A node whose kind is already known to be accepted.</param>
        private Comment(global::TreeSitter.Node node)
        {
            Node = node;
        }

        /// <summary>Determines whether a node of the given kind is accepted by this type.</summary>
        /// <param name="kind">A node kind string.</param>
        public static bool Accepts(string kind) => kind == Kind;

        /// <summary>Wraps the node if its kind is accepted, otherwise returns <see langword="null"/>.</summary>
        /// <param name="node">The node to wrap.</param>
        public static Comment? TryFrom(global::TreeSitter.Node node) => !node.IsNull && Accepts(node.Kind) ? new Comment(node) : null;

        /// <summary>Wraps the node without validation; a debug assert guards the kind. Use only when the kind is already known.</summary>
        /// <param name="node">An already-validated node.</param>
        public static Comment FromUnchecked(global::TreeSitter.Node node)
        {
            global::System.Diagnostics.Debug.Assert(Accepts(node.Kind), "Node kind '" + node.Kind + "' is not valid for Comment.");
            return new(node);
        }
    }

    /// <summary>The <c>document</c> node.</summary>
    public readonly partial struct Document : global::TreeSitter.Typed.ITypedNode<Document>
    {

        /// <summary>The s-expression kind string for this node type.</summary>
        public const string Kind = "document";

        /// <summary>The underlying untyped node.</summary>
        public global::TreeSitter.Node Node { get; }

        /// <summary>Wraps <paramref name="node"/> as a <see cref="Document"/> without any kind check.</summary>
        /// <param name="node">A node whose kind is already known to be accepted.</param>
        private Document(global::TreeSitter.Node node)
        {
            Node = node;
        }

        /// <summary>Determines whether a node of the given kind is accepted by this type.</summary>
        /// <param name="kind">A node kind string.</param>
        public static bool Accepts(string kind) => kind == Kind;

        /// <summary>Wraps the node if its kind is accepted, otherwise returns <see langword="null"/>.</summary>
        /// <param name="node">The node to wrap.</param>
        public static Document? TryFrom(global::TreeSitter.Node node) => !node.IsNull && Accepts(node.Kind) ? new Document(node) : null;

        /// <summary>Wraps the node without validation; a debug assert guards the kind. Use only when the kind is already known.</summary>
        /// <param name="node">An already-validated node.</param>
        public static Document FromUnchecked(global::TreeSitter.Node node)
        {
            global::System.Diagnostics.Debug.Assert(Accepts(node.Kind), "Node kind '" + node.Kind + "' is not valid for Document.");
            return new(node);
        }
        /// <summary>The unnamed children (zero or more), with extras filtered out.</summary>
        public global::System.Collections.Generic.IEnumerable<TreeSitter.Grammars.Json.Value> Values
        {
            get
            {
                foreach (global::TreeSitter.Node child in global::TreeSitter.Typed.TypedNodeExtensions.FieldlessChildren(Node))
                {
                    if (TreeSitter.Grammars.Json.Value.TryFrom(child) is { } typed) yield return typed;
                }
            }
        }

    }

    /// <summary>The <c>escape_sequence</c> node.</summary>
    public readonly partial struct EscapeSequence : global::TreeSitter.Typed.ITypedNode<EscapeSequence>
    {

        /// <summary>The s-expression kind string for this node type.</summary>
        public const string Kind = "escape_sequence";

        /// <summary>The underlying untyped node.</summary>
        public global::TreeSitter.Node Node { get; }

        /// <summary>Wraps <paramref name="node"/> as a <see cref="EscapeSequence"/> without any kind check.</summary>
        /// <param name="node">A node whose kind is already known to be accepted.</param>
        private EscapeSequence(global::TreeSitter.Node node)
        {
            Node = node;
        }

        /// <summary>Determines whether a node of the given kind is accepted by this type.</summary>
        /// <param name="kind">A node kind string.</param>
        public static bool Accepts(string kind) => kind == Kind;

        /// <summary>Wraps the node if its kind is accepted, otherwise returns <see langword="null"/>.</summary>
        /// <param name="node">The node to wrap.</param>
        public static EscapeSequence? TryFrom(global::TreeSitter.Node node) => !node.IsNull && Accepts(node.Kind) ? new EscapeSequence(node) : null;

        /// <summary>Wraps the node without validation; a debug assert guards the kind. Use only when the kind is already known.</summary>
        /// <param name="node">An already-validated node.</param>
        public static EscapeSequence FromUnchecked(global::TreeSitter.Node node)
        {
            global::System.Diagnostics.Debug.Assert(Accepts(node.Kind), "Node kind '" + node.Kind + "' is not valid for EscapeSequence.");
            return new(node);
        }
    }

    /// <summary>The <c>false</c> node.</summary>
    public readonly partial struct False : global::TreeSitter.Typed.ITypedNode<False>
    {

        /// <summary>The s-expression kind string for this node type.</summary>
        public const string Kind = "false";

        /// <summary>The underlying untyped node.</summary>
        public global::TreeSitter.Node Node { get; }

        /// <summary>Wraps <paramref name="node"/> as a <see cref="False"/> without any kind check.</summary>
        /// <param name="node">A node whose kind is already known to be accepted.</param>
        private False(global::TreeSitter.Node node)
        {
            Node = node;
        }

        /// <summary>Determines whether a node of the given kind is accepted by this type.</summary>
        /// <param name="kind">A node kind string.</param>
        public static bool Accepts(string kind) => kind == Kind;

        /// <summary>Wraps the node if its kind is accepted, otherwise returns <see langword="null"/>.</summary>
        /// <param name="node">The node to wrap.</param>
        public static False? TryFrom(global::TreeSitter.Node node) => !node.IsNull && Accepts(node.Kind) ? new False(node) : null;

        /// <summary>Wraps the node without validation; a debug assert guards the kind. Use only when the kind is already known.</summary>
        /// <param name="node">An already-validated node.</param>
        public static False FromUnchecked(global::TreeSitter.Node node)
        {
            global::System.Diagnostics.Debug.Assert(Accepts(node.Kind), "Node kind '" + node.Kind + "' is not valid for False.");
            return new(node);
        }
    }

    /// <summary>The <c>null</c> node.</summary>
    public readonly partial struct Null : global::TreeSitter.Typed.ITypedNode<Null>
    {

        /// <summary>The s-expression kind string for this node type.</summary>
        public const string Kind = "null";

        /// <summary>The underlying untyped node.</summary>
        public global::TreeSitter.Node Node { get; }

        /// <summary>Wraps <paramref name="node"/> as a <see cref="Null"/> without any kind check.</summary>
        /// <param name="node">A node whose kind is already known to be accepted.</param>
        private Null(global::TreeSitter.Node node)
        {
            Node = node;
        }

        /// <summary>Determines whether a node of the given kind is accepted by this type.</summary>
        /// <param name="kind">A node kind string.</param>
        public static bool Accepts(string kind) => kind == Kind;

        /// <summary>Wraps the node if its kind is accepted, otherwise returns <see langword="null"/>.</summary>
        /// <param name="node">The node to wrap.</param>
        public static Null? TryFrom(global::TreeSitter.Node node) => !node.IsNull && Accepts(node.Kind) ? new Null(node) : null;

        /// <summary>Wraps the node without validation; a debug assert guards the kind. Use only when the kind is already known.</summary>
        /// <param name="node">An already-validated node.</param>
        public static Null FromUnchecked(global::TreeSitter.Node node)
        {
            global::System.Diagnostics.Debug.Assert(Accepts(node.Kind), "Node kind '" + node.Kind + "' is not valid for Null.");
            return new(node);
        }
    }

    /// <summary>The <c>number</c> node.</summary>
    public readonly partial struct Number : global::TreeSitter.Typed.ITypedNode<Number>
    {

        /// <summary>The s-expression kind string for this node type.</summary>
        public const string Kind = "number";

        /// <summary>The underlying untyped node.</summary>
        public global::TreeSitter.Node Node { get; }

        /// <summary>Wraps <paramref name="node"/> as a <see cref="Number"/> without any kind check.</summary>
        /// <param name="node">A node whose kind is already known to be accepted.</param>
        private Number(global::TreeSitter.Node node)
        {
            Node = node;
        }

        /// <summary>Determines whether a node of the given kind is accepted by this type.</summary>
        /// <param name="kind">A node kind string.</param>
        public static bool Accepts(string kind) => kind == Kind;

        /// <summary>Wraps the node if its kind is accepted, otherwise returns <see langword="null"/>.</summary>
        /// <param name="node">The node to wrap.</param>
        public static Number? TryFrom(global::TreeSitter.Node node) => !node.IsNull && Accepts(node.Kind) ? new Number(node) : null;

        /// <summary>Wraps the node without validation; a debug assert guards the kind. Use only when the kind is already known.</summary>
        /// <param name="node">An already-validated node.</param>
        public static Number FromUnchecked(global::TreeSitter.Node node)
        {
            global::System.Diagnostics.Debug.Assert(Accepts(node.Kind), "Node kind '" + node.Kind + "' is not valid for Number.");
            return new(node);
        }
    }

    /// <summary>The <c>object</c> node.</summary>
    public readonly partial struct Object : global::TreeSitter.Typed.ITypedNode<Object>
    {

        /// <summary>The s-expression kind string for this node type.</summary>
        public const string Kind = "object";

        /// <summary>The underlying untyped node.</summary>
        public global::TreeSitter.Node Node { get; }

        /// <summary>Wraps <paramref name="node"/> as a <see cref="Object"/> without any kind check.</summary>
        /// <param name="node">A node whose kind is already known to be accepted.</param>
        private Object(global::TreeSitter.Node node)
        {
            Node = node;
        }

        /// <summary>Determines whether a node of the given kind is accepted by this type.</summary>
        /// <param name="kind">A node kind string.</param>
        public static bool Accepts(string kind) => kind == Kind;

        /// <summary>Wraps the node if its kind is accepted, otherwise returns <see langword="null"/>.</summary>
        /// <param name="node">The node to wrap.</param>
        public static Object? TryFrom(global::TreeSitter.Node node) => !node.IsNull && Accepts(node.Kind) ? new Object(node) : null;

        /// <summary>Wraps the node without validation; a debug assert guards the kind. Use only when the kind is already known.</summary>
        /// <param name="node">An already-validated node.</param>
        public static Object FromUnchecked(global::TreeSitter.Node node)
        {
            global::System.Diagnostics.Debug.Assert(Accepts(node.Kind), "Node kind '" + node.Kind + "' is not valid for Object.");
            return new(node);
        }
        /// <summary>The unnamed children (zero or more), with extras filtered out.</summary>
        public global::System.Collections.Generic.IEnumerable<TreeSitter.Grammars.Json.Pair> Pairs
        {
            get
            {
                foreach (global::TreeSitter.Node child in global::TreeSitter.Typed.TypedNodeExtensions.FieldlessChildren(Node))
                {
                    if (TreeSitter.Grammars.Json.Pair.TryFrom(child) is { } typed) yield return typed;
                }
            }
        }

    }

    /// <summary>The <c>pair</c> node.</summary>
    public readonly partial struct Pair : global::TreeSitter.Typed.ITypedNode<Pair>
    {

        /// <summary>The s-expression kind string for this node type.</summary>
        public const string Kind = "pair";

        /// <summary>The underlying untyped node.</summary>
        public global::TreeSitter.Node Node { get; }

        /// <summary>Wraps <paramref name="node"/> as a <see cref="Pair"/> without any kind check.</summary>
        /// <param name="node">A node whose kind is already known to be accepted.</param>
        private Pair(global::TreeSitter.Node node)
        {
            Node = node;
        }

        /// <summary>Determines whether a node of the given kind is accepted by this type.</summary>
        /// <param name="kind">A node kind string.</param>
        public static bool Accepts(string kind) => kind == Kind;

        /// <summary>Wraps the node if its kind is accepted, otherwise returns <see langword="null"/>.</summary>
        /// <param name="node">The node to wrap.</param>
        public static Pair? TryFrom(global::TreeSitter.Node node) => !node.IsNull && Accepts(node.Kind) ? new Pair(node) : null;

        /// <summary>Wraps the node without validation; a debug assert guards the kind. Use only when the kind is already known.</summary>
        /// <param name="node">An already-validated node.</param>
        public static Pair FromUnchecked(global::TreeSitter.Node node)
        {
            global::System.Diagnostics.Debug.Assert(Accepts(node.Kind), "Node kind '" + node.Kind + "' is not valid for Pair.");
            return new(node);
        }
        /// <summary>The required <c>key</c> field.</summary>
        /// <exception cref="global::TreeSitter.Typed.IncorrectNodeKindException">The field is absent or has an unexpected kind.</exception>
        public TreeSitter.Grammars.Json.String Key => TreeSitter.Grammars.Json.String.TryFrom(Node.ChildByFieldName("key")) ?? throw new global::TreeSitter.Typed.IncorrectNodeKindException(Node, "TreeSitter.Grammars.Json.String");

        /// <summary>The required <c>value</c> field.</summary>
        /// <exception cref="global::TreeSitter.Typed.IncorrectNodeKindException">The field is absent or has an unexpected kind.</exception>
        public TreeSitter.Grammars.Json.Value Value => TreeSitter.Grammars.Json.Value.TryFrom(Node.ChildByFieldName("value")) ?? throw new global::TreeSitter.Typed.IncorrectNodeKindException(Node, "TreeSitter.Grammars.Json.Value");

    }

    /// <summary>The <c>string</c> node.</summary>
    public readonly partial struct String : global::TreeSitter.Typed.ITypedNode<String>
    {

        /// <summary>The s-expression kind string for this node type.</summary>
        public const string Kind = "string";

        /// <summary>The underlying untyped node.</summary>
        public global::TreeSitter.Node Node { get; }

        /// <summary>Wraps <paramref name="node"/> as a <see cref="String"/> without any kind check.</summary>
        /// <param name="node">A node whose kind is already known to be accepted.</param>
        private String(global::TreeSitter.Node node)
        {
            Node = node;
        }

        /// <summary>Determines whether a node of the given kind is accepted by this type.</summary>
        /// <param name="kind">A node kind string.</param>
        public static bool Accepts(string kind) => kind == Kind;

        /// <summary>Wraps the node if its kind is accepted, otherwise returns <see langword="null"/>.</summary>
        /// <param name="node">The node to wrap.</param>
        public static String? TryFrom(global::TreeSitter.Node node) => !node.IsNull && Accepts(node.Kind) ? new String(node) : null;

        /// <summary>Wraps the node without validation; a debug assert guards the kind. Use only when the kind is already known.</summary>
        /// <param name="node">An already-validated node.</param>
        public static String FromUnchecked(global::TreeSitter.Node node)
        {
            global::System.Diagnostics.Debug.Assert(Accepts(node.Kind), "Node kind '" + node.Kind + "' is not valid for String.");
            return new(node);
        }
        /// <summary>The unnamed children (zero or more), with extras filtered out.</summary>
        public global::System.Collections.Generic.IEnumerable<TreeSitter.Grammars.Json.AnonUnions.EscapeSequence_StringContent> Children
        {
            get
            {
                foreach (global::TreeSitter.Node child in global::TreeSitter.Typed.TypedNodeExtensions.FieldlessChildren(Node))
                {
                    if (TreeSitter.Grammars.Json.AnonUnions.EscapeSequence_StringContent.TryFrom(child) is { } typed) yield return typed;
                }
            }
        }

    }

    /// <summary>The <c>string_content</c> node.</summary>
    public readonly partial struct StringContent : global::TreeSitter.Typed.ITypedNode<StringContent>
    {

        /// <summary>The s-expression kind string for this node type.</summary>
        public const string Kind = "string_content";

        /// <summary>The underlying untyped node.</summary>
        public global::TreeSitter.Node Node { get; }

        /// <summary>Wraps <paramref name="node"/> as a <see cref="StringContent"/> without any kind check.</summary>
        /// <param name="node">A node whose kind is already known to be accepted.</param>
        private StringContent(global::TreeSitter.Node node)
        {
            Node = node;
        }

        /// <summary>Determines whether a node of the given kind is accepted by this type.</summary>
        /// <param name="kind">A node kind string.</param>
        public static bool Accepts(string kind) => kind == Kind;

        /// <summary>Wraps the node if its kind is accepted, otherwise returns <see langword="null"/>.</summary>
        /// <param name="node">The node to wrap.</param>
        public static StringContent? TryFrom(global::TreeSitter.Node node) => !node.IsNull && Accepts(node.Kind) ? new StringContent(node) : null;

        /// <summary>Wraps the node without validation; a debug assert guards the kind. Use only when the kind is already known.</summary>
        /// <param name="node">An already-validated node.</param>
        public static StringContent FromUnchecked(global::TreeSitter.Node node)
        {
            global::System.Diagnostics.Debug.Assert(Accepts(node.Kind), "Node kind '" + node.Kind + "' is not valid for StringContent.");
            return new(node);
        }
    }

    /// <summary>The <c>true</c> node.</summary>
    public readonly partial struct True : global::TreeSitter.Typed.ITypedNode<True>
    {

        /// <summary>The s-expression kind string for this node type.</summary>
        public const string Kind = "true";

        /// <summary>The underlying untyped node.</summary>
        public global::TreeSitter.Node Node { get; }

        /// <summary>Wraps <paramref name="node"/> as a <see cref="True"/> without any kind check.</summary>
        /// <param name="node">A node whose kind is already known to be accepted.</param>
        private True(global::TreeSitter.Node node)
        {
            Node = node;
        }

        /// <summary>Determines whether a node of the given kind is accepted by this type.</summary>
        /// <param name="kind">A node kind string.</param>
        public static bool Accepts(string kind) => kind == Kind;

        /// <summary>Wraps the node if its kind is accepted, otherwise returns <see langword="null"/>.</summary>
        /// <param name="node">The node to wrap.</param>
        public static True? TryFrom(global::TreeSitter.Node node) => !node.IsNull && Accepts(node.Kind) ? new True(node) : null;

        /// <summary>Wraps the node without validation; a debug assert guards the kind. Use only when the kind is already known.</summary>
        /// <param name="node">An already-validated node.</param>
        public static True FromUnchecked(global::TreeSitter.Node node)
        {
            global::System.Diagnostics.Debug.Assert(Accepts(node.Kind), "Node kind '" + node.Kind + "' is not valid for True.");
            return new(node);
        }
    }

}

namespace TreeSitter.Grammars.Json.Symbols
{
    /// <summary>The <c>"</c> token.</summary>
    public readonly partial struct Quote : global::TreeSitter.Typed.ITypedNode<Quote>
    {

        /// <summary>The s-expression kind string for this node type.</summary>
        public const string Kind = "\"";

        /// <summary>The underlying untyped node.</summary>
        public global::TreeSitter.Node Node { get; }

        /// <summary>Wraps <paramref name="node"/> as a <see cref="Quote"/> without any kind check.</summary>
        /// <param name="node">A node whose kind is already known to be accepted.</param>
        private Quote(global::TreeSitter.Node node)
        {
            Node = node;
        }

        /// <summary>Determines whether a node of the given kind is accepted by this type.</summary>
        /// <param name="kind">A node kind string.</param>
        public static bool Accepts(string kind) => kind == Kind;

        /// <summary>Wraps the node if its kind is accepted, otherwise returns <see langword="null"/>.</summary>
        /// <param name="node">The node to wrap.</param>
        public static Quote? TryFrom(global::TreeSitter.Node node) => !node.IsNull && Accepts(node.Kind) ? new Quote(node) : null;

        /// <summary>Wraps the node without validation; a debug assert guards the kind. Use only when the kind is already known.</summary>
        /// <param name="node">An already-validated node.</param>
        public static Quote FromUnchecked(global::TreeSitter.Node node)
        {
            global::System.Diagnostics.Debug.Assert(Accepts(node.Kind), "Node kind '" + node.Kind + "' is not valid for Quote.");
            return new(node);
        }
    }

    /// <summary>The <c>,</c> token.</summary>
    public readonly partial struct Comma : global::TreeSitter.Typed.ITypedNode<Comma>
    {

        /// <summary>The s-expression kind string for this node type.</summary>
        public const string Kind = ",";

        /// <summary>The underlying untyped node.</summary>
        public global::TreeSitter.Node Node { get; }

        /// <summary>Wraps <paramref name="node"/> as a <see cref="Comma"/> without any kind check.</summary>
        /// <param name="node">A node whose kind is already known to be accepted.</param>
        private Comma(global::TreeSitter.Node node)
        {
            Node = node;
        }

        /// <summary>Determines whether a node of the given kind is accepted by this type.</summary>
        /// <param name="kind">A node kind string.</param>
        public static bool Accepts(string kind) => kind == Kind;

        /// <summary>Wraps the node if its kind is accepted, otherwise returns <see langword="null"/>.</summary>
        /// <param name="node">The node to wrap.</param>
        public static Comma? TryFrom(global::TreeSitter.Node node) => !node.IsNull && Accepts(node.Kind) ? new Comma(node) : null;

        /// <summary>Wraps the node without validation; a debug assert guards the kind. Use only when the kind is already known.</summary>
        /// <param name="node">An already-validated node.</param>
        public static Comma FromUnchecked(global::TreeSitter.Node node)
        {
            global::System.Diagnostics.Debug.Assert(Accepts(node.Kind), "Node kind '" + node.Kind + "' is not valid for Comma.");
            return new(node);
        }
    }

    /// <summary>The <c>:</c> token.</summary>
    public readonly partial struct Colon : global::TreeSitter.Typed.ITypedNode<Colon>
    {

        /// <summary>The s-expression kind string for this node type.</summary>
        public const string Kind = ":";

        /// <summary>The underlying untyped node.</summary>
        public global::TreeSitter.Node Node { get; }

        /// <summary>Wraps <paramref name="node"/> as a <see cref="Colon"/> without any kind check.</summary>
        /// <param name="node">A node whose kind is already known to be accepted.</param>
        private Colon(global::TreeSitter.Node node)
        {
            Node = node;
        }

        /// <summary>Determines whether a node of the given kind is accepted by this type.</summary>
        /// <param name="kind">A node kind string.</param>
        public static bool Accepts(string kind) => kind == Kind;

        /// <summary>Wraps the node if its kind is accepted, otherwise returns <see langword="null"/>.</summary>
        /// <param name="node">The node to wrap.</param>
        public static Colon? TryFrom(global::TreeSitter.Node node) => !node.IsNull && Accepts(node.Kind) ? new Colon(node) : null;

        /// <summary>Wraps the node without validation; a debug assert guards the kind. Use only when the kind is already known.</summary>
        /// <param name="node">An already-validated node.</param>
        public static Colon FromUnchecked(global::TreeSitter.Node node)
        {
            global::System.Diagnostics.Debug.Assert(Accepts(node.Kind), "Node kind '" + node.Kind + "' is not valid for Colon.");
            return new(node);
        }
    }

    /// <summary>The <c>[</c> token.</summary>
    public readonly partial struct LBracket : global::TreeSitter.Typed.ITypedNode<LBracket>
    {

        /// <summary>The s-expression kind string for this node type.</summary>
        public const string Kind = "[";

        /// <summary>The underlying untyped node.</summary>
        public global::TreeSitter.Node Node { get; }

        /// <summary>Wraps <paramref name="node"/> as a <see cref="LBracket"/> without any kind check.</summary>
        /// <param name="node">A node whose kind is already known to be accepted.</param>
        private LBracket(global::TreeSitter.Node node)
        {
            Node = node;
        }

        /// <summary>Determines whether a node of the given kind is accepted by this type.</summary>
        /// <param name="kind">A node kind string.</param>
        public static bool Accepts(string kind) => kind == Kind;

        /// <summary>Wraps the node if its kind is accepted, otherwise returns <see langword="null"/>.</summary>
        /// <param name="node">The node to wrap.</param>
        public static LBracket? TryFrom(global::TreeSitter.Node node) => !node.IsNull && Accepts(node.Kind) ? new LBracket(node) : null;

        /// <summary>Wraps the node without validation; a debug assert guards the kind. Use only when the kind is already known.</summary>
        /// <param name="node">An already-validated node.</param>
        public static LBracket FromUnchecked(global::TreeSitter.Node node)
        {
            global::System.Diagnostics.Debug.Assert(Accepts(node.Kind), "Node kind '" + node.Kind + "' is not valid for LBracket.");
            return new(node);
        }
    }

    /// <summary>The <c>]</c> token.</summary>
    public readonly partial struct RBracket : global::TreeSitter.Typed.ITypedNode<RBracket>
    {

        /// <summary>The s-expression kind string for this node type.</summary>
        public const string Kind = "]";

        /// <summary>The underlying untyped node.</summary>
        public global::TreeSitter.Node Node { get; }

        /// <summary>Wraps <paramref name="node"/> as a <see cref="RBracket"/> without any kind check.</summary>
        /// <param name="node">A node whose kind is already known to be accepted.</param>
        private RBracket(global::TreeSitter.Node node)
        {
            Node = node;
        }

        /// <summary>Determines whether a node of the given kind is accepted by this type.</summary>
        /// <param name="kind">A node kind string.</param>
        public static bool Accepts(string kind) => kind == Kind;

        /// <summary>Wraps the node if its kind is accepted, otherwise returns <see langword="null"/>.</summary>
        /// <param name="node">The node to wrap.</param>
        public static RBracket? TryFrom(global::TreeSitter.Node node) => !node.IsNull && Accepts(node.Kind) ? new RBracket(node) : null;

        /// <summary>Wraps the node without validation; a debug assert guards the kind. Use only when the kind is already known.</summary>
        /// <param name="node">An already-validated node.</param>
        public static RBracket FromUnchecked(global::TreeSitter.Node node)
        {
            global::System.Diagnostics.Debug.Assert(Accepts(node.Kind), "Node kind '" + node.Kind + "' is not valid for RBracket.");
            return new(node);
        }
    }

    /// <summary>The <c>{</c> token.</summary>
    public readonly partial struct LBrace : global::TreeSitter.Typed.ITypedNode<LBrace>
    {

        /// <summary>The s-expression kind string for this node type.</summary>
        public const string Kind = "{";

        /// <summary>The underlying untyped node.</summary>
        public global::TreeSitter.Node Node { get; }

        /// <summary>Wraps <paramref name="node"/> as a <see cref="LBrace"/> without any kind check.</summary>
        /// <param name="node">A node whose kind is already known to be accepted.</param>
        private LBrace(global::TreeSitter.Node node)
        {
            Node = node;
        }

        /// <summary>Determines whether a node of the given kind is accepted by this type.</summary>
        /// <param name="kind">A node kind string.</param>
        public static bool Accepts(string kind) => kind == Kind;

        /// <summary>Wraps the node if its kind is accepted, otherwise returns <see langword="null"/>.</summary>
        /// <param name="node">The node to wrap.</param>
        public static LBrace? TryFrom(global::TreeSitter.Node node) => !node.IsNull && Accepts(node.Kind) ? new LBrace(node) : null;

        /// <summary>Wraps the node without validation; a debug assert guards the kind. Use only when the kind is already known.</summary>
        /// <param name="node">An already-validated node.</param>
        public static LBrace FromUnchecked(global::TreeSitter.Node node)
        {
            global::System.Diagnostics.Debug.Assert(Accepts(node.Kind), "Node kind '" + node.Kind + "' is not valid for LBrace.");
            return new(node);
        }
    }

    /// <summary>The <c>}</c> token.</summary>
    public readonly partial struct RBrace : global::TreeSitter.Typed.ITypedNode<RBrace>
    {

        /// <summary>The s-expression kind string for this node type.</summary>
        public const string Kind = "}";

        /// <summary>The underlying untyped node.</summary>
        public global::TreeSitter.Node Node { get; }

        /// <summary>Wraps <paramref name="node"/> as a <see cref="RBrace"/> without any kind check.</summary>
        /// <param name="node">A node whose kind is already known to be accepted.</param>
        private RBrace(global::TreeSitter.Node node)
        {
            Node = node;
        }

        /// <summary>Determines whether a node of the given kind is accepted by this type.</summary>
        /// <param name="kind">A node kind string.</param>
        public static bool Accepts(string kind) => kind == Kind;

        /// <summary>Wraps the node if its kind is accepted, otherwise returns <see langword="null"/>.</summary>
        /// <param name="node">The node to wrap.</param>
        public static RBrace? TryFrom(global::TreeSitter.Node node) => !node.IsNull && Accepts(node.Kind) ? new RBrace(node) : null;

        /// <summary>Wraps the node without validation; a debug assert guards the kind. Use only when the kind is already known.</summary>
        /// <param name="node">An already-validated node.</param>
        public static RBrace FromUnchecked(global::TreeSitter.Node node)
        {
            global::System.Diagnostics.Debug.Assert(Accepts(node.Kind), "Node kind '" + node.Kind + "' is not valid for RBrace.");
            return new(node);
        }
    }

}

namespace TreeSitter.Grammars.Json.AnonUnions
{
    /// <summary>An anonymous union generated for a multi-type field or children group.</summary>
    public readonly partial struct EscapeSequence_StringContent : global::TreeSitter.Typed.ITypedNode<EscapeSequence_StringContent>
    {

        /// <summary>The underlying untyped node.</summary>
        public global::TreeSitter.Node Node { get; }

        /// <summary>Wraps <paramref name="node"/> as a <see cref="EscapeSequence_StringContent"/> without any kind check.</summary>
        /// <param name="node">A node whose kind is already known to be accepted.</param>
        private EscapeSequence_StringContent(global::TreeSitter.Node node)
        {
            Node = node;
        }

        /// <summary>Determines whether a node of the given kind is accepted by this union.</summary>
        /// <param name="kind">A node kind string.</param>
        public static bool Accepts(string kind) => kind switch
        {
            "escape_sequence" => true,
            "string_content" => true,
            _ => false,
        };

        /// <summary>Wraps the node if its kind is accepted, otherwise returns <see langword="null"/>.</summary>
        /// <param name="node">The node to wrap.</param>
        public static EscapeSequence_StringContent? TryFrom(global::TreeSitter.Node node) => !node.IsNull && Accepts(node.Kind) ? new EscapeSequence_StringContent(node) : null;

        /// <summary>Wraps the node without validation; a debug assert guards the kind. Use only when the kind is already known.</summary>
        /// <param name="node">An already-validated node.</param>
        public static EscapeSequence_StringContent FromUnchecked(global::TreeSitter.Node node)
        {
            global::System.Diagnostics.Debug.Assert(Accepts(node.Kind), "Node kind '" + node.Kind + "' is not valid for EscapeSequence_StringContent.");
            return new(node);
        }

        /// <summary>Discriminates which variant the wrapped node is.</summary>
        public enum Variant
        {
            /// <summary>The node matched no known variant.</summary>
            Unknown,
            /// <summary>The <c>escape_sequence</c> variant.</summary>
            EscapeSequence,
            /// <summary>The <c>string_content</c> variant.</summary>
            StringContent,
        }

        /// <summary>The variant of the wrapped node. When variants overlap, the first declared variant that accepts the kind is reported.</summary>
        public Variant Which => Node.Kind switch
        {
            "escape_sequence" => Variant.EscapeSequence,
            "string_content" => Variant.StringContent,
            _ => Variant.Unknown,
        };

        /// <summary>The node as <see cref="TreeSitter.Grammars.Json.EscapeSequence"/>, or <see langword="null"/> if it is a different variant.</summary>
        public TreeSitter.Grammars.Json.EscapeSequence? AsEscapeSequence() => TreeSitter.Grammars.Json.EscapeSequence.TryFrom(Node);

        /// <summary>The node as <see cref="TreeSitter.Grammars.Json.StringContent"/>, or <see langword="null"/> if it is a different variant.</summary>
        public TreeSitter.Grammars.Json.StringContent? AsStringContent() => TreeSitter.Grammars.Json.StringContent.TryFrom(Node);

        /// <summary>Exhaustively maps over the variants, returning a value.</summary>
        public TResult Match<TResult>(global::System.Func<TreeSitter.Grammars.Json.EscapeSequence, TResult> onEscapeSequence, global::System.Func<TreeSitter.Grammars.Json.StringContent, TResult> onStringContent)
        {
            return Which switch
            {
                Variant.EscapeSequence => onEscapeSequence(TreeSitter.Grammars.Json.EscapeSequence.FromUnchecked(Node)),
                Variant.StringContent => onStringContent(TreeSitter.Grammars.Json.StringContent.FromUnchecked(Node)),
                _ => throw new global::TreeSitter.Typed.IncorrectNodeKindException(Node, "EscapeSequence_StringContent"),
            };
        }

        /// <summary>Exhaustively dispatches over the variants, performing an action.</summary>
        public void Switch(global::System.Action<TreeSitter.Grammars.Json.EscapeSequence> onEscapeSequence, global::System.Action<TreeSitter.Grammars.Json.StringContent> onStringContent)
        {
            switch (Which)
            {
                case Variant.EscapeSequence: onEscapeSequence(TreeSitter.Grammars.Json.EscapeSequence.FromUnchecked(Node)); break;
                case Variant.StringContent: onStringContent(TreeSitter.Grammars.Json.StringContent.FromUnchecked(Node)); break;
                default: throw new global::TreeSitter.Typed.IncorrectNodeKindException(Node, "EscapeSequence_StringContent");
            }
        }

    }

}

