using TreeSitter;
using TreeSitter.Grammars.Python;
using Py = TreeSitter.Grammars.Python;

namespace TreeSitter.Tests;

/// <summary>
/// End-to-end test of the "easy typed parser" story for a second language: resolve the
/// Python grammar by name via <see cref="PythonLanguage"/> (backed by LanguagePack) and
/// navigate a strongly-typed syntax tree generated by tsgen.
/// </summary>
public class PythonTypedTreeTests
{
    private const string Source = "def greet(name):\n    return name\n";

    [Fact]
    public void PythonLanguage_exposes_the_grammar()
    {
        Language lang = PythonLanguage.Language;
        Assert.NotNull(lang);
        // The python grammar is ABI 15, so it reports its name.
        Assert.Equal("python", lang.Name);
        Assert.Same(PythonLanguage.Language, lang); // cached
    }

    [Fact]
    public void CreateParser_produces_a_module_root()
    {
        using Parser parser = PythonLanguage.CreateParser();
        using Tree? tree = parser.Parse(Source);
        Assert.NotNull(tree);

        Py.Module? module = Py.Module.TryFrom(tree!.RootNode);
        Assert.NotNull(module);
        Assert.Equal("module", module!.Value.Node.Kind);
        Assert.False(tree.RootNode.HasError);
    }

    [Fact]
    public void Navigate_module_to_function_definition_name()
    {
        using Parser parser = PythonLanguage.CreateParser();
        using Tree? tree = parser.Parse(Source);
        Assert.NotNull(tree);

        Py.Module module = Py.Module.TryFrom(tree!.RootNode)!.Value;

        // module -> function_definition (first compound/simple statement child).
        Py.FunctionDefinition? func = module.Children
            .Select(static c => Py.FunctionDefinition.TryFrom(c.Node))
            .FirstOrDefault(static f => f is not null);
        Assert.NotNull(func);

        // function_definition -> name identifier (typed field accessor).
        Py.Identifier name = func!.Value.Name;
        Assert.Equal("identifier", name.Node.Kind);
        Assert.Equal("greet", name.Node.Text);

        // The body is a typed block, and the parameters are a typed node.
        Assert.Equal("block", func.Value.Body.Node.Kind);
        Assert.Equal("parameters", func.Value.Parameters.Node.Kind);
    }

    [Fact]
    public void Sanitizer_emits_csharp_keyword_node_types_as_valid_types()
    {
        // Python has node types named like C# keywords (`class`, `if`, `for`, `while`,
        // `return`, `true`/`false`, `string`). tsgen must sanitize these into valid C#
        // identifiers while preserving the original Kind string. The unnamed-token
        // structs live in the nested 'Unnamed' namespace. Verify a few compile and
        // round-trip via Accepts/Kind.
        // Unnamed keyword tokens (class/if/for/while/return) live in the nested
        // 'Unnamed' namespace; the named boolean literals (true/false) are root types.
        Assert.Equal("class", Py.Unnamed.Class.Kind);
        Assert.True(Py.Unnamed.Class.Accepts("class"));
        Assert.Equal("if", Py.Unnamed.If.Kind);
        Assert.Equal("for", Py.Unnamed.For.Kind);
        Assert.Equal("while", Py.Unnamed.While.Kind);
        Assert.Equal("return", Py.Unnamed.Return.Kind);
        Assert.Equal("true", Py.True.Kind);
        Assert.Equal("false", Py.False.Kind);
    }

    [Fact]
    public void Typed_return_statement_is_reachable_in_the_tree()
    {
        using Parser parser = PythonLanguage.CreateParser();
        using Tree? tree = parser.Parse(Source);
        Assert.NotNull(tree);

        // Walk to the return_statement inside the function body and confirm its text.
        Node returnNode = FindFirst(tree!.RootNode, "return_statement");
        Assert.False(returnNode.IsNull);
        Assert.StartsWith("return", returnNode.Text);
    }

    private static Node FindFirst(Node node, string kind)
    {
        if (node.Kind == kind)
            return node;
        uint count = node.NamedChildCount;
        for (uint i = 0; i < count; i++)
        {
            Node found = FindFirst(node.NamedChild(i), kind);
            if (!found.IsNull)
                return found;
        }
        return default;
    }
}
